# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'details_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_details(object):
    def setupUi(self, details):
        details.setObjectName("details")
        details.resize(1241, 901)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(details.sizePolicy().hasHeightForWidth())
        details.setSizePolicy(sizePolicy)
        details.setMaximumSize(QtCore.QSize(16777215, 16777215))
        details.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffff;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"    color: #0000;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #3E2723;\n"
"    background-color: #D7CCC8;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"   background-color: white;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"   background-color: white;\n"
"}\n"
"QMenuBar{\n"
"    background: #BCAAA4;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: #BCAAA4;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    color: #fff;\n"
"    background: #BCAAA4;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"     border: 1px solid #000;\n"
"    background-color: #D7CCC8;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: white;\n"
"    color:#000;\n"
"}\n"
"\n"
"\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"   /* background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;*/\n"
"\n"
"background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #000;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
" /*   border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"   /* background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);*/\n"
"    selection-background-color: #000;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"   /* selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"\n"
"background-color: #000000 ;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:rgba(66,66,66,0%);\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QGroupBox{\n"
"  background-color: #BCAAA4;\n"
"  border-radius:15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #242424;\n"
" background-color: #D7CCC8;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #3E2723;\n"
"    width: 5px;\n"
"    border-radius: 5px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton{\n"
"background-color:rgba(66,66,66,0%);\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 6;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox\n"
"{\n"
"    border-radius: 6;\n"
"    padding:5px\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    \n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(details)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(details)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1221, 881))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_19 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.line_42 = QtWidgets.QFrame(self.groupBox_19)
        self.line_42.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.verticalLayout_11.addWidget(self.line_42)
        self.label_42 = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_11.addWidget(self.label_42)
        self.line_43 = QtWidgets.QFrame(self.groupBox_19)
        self.line_43.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.verticalLayout_11.addWidget(self.line_43)
        self.fYarn = QtWidgets.QFrame(self.groupBox_19)
        self.fYarn.setStyleSheet(" border-radius:10px;")
        self.fYarn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fYarn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fYarn.setObjectName("fYarn")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fYarn)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnYarn = QtWidgets.QPushButton(self.fYarn)
        self.btnYarn.setObjectName("btnYarn")
        self.horizontalLayout_6.addWidget(self.btnYarn)
        self.comYarn = QtWidgets.QComboBox(self.fYarn)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comYarn.setFont(font)
        self.comYarn.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comYarn.setEditable(True)
        self.comYarn.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comYarn.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comYarn.setObjectName("comYarn")
        self.horizontalLayout_6.addWidget(self.comYarn)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_11.addWidget(self.fYarn)
        self.twYarn = QtWidgets.QTableWidget(self.groupBox_19)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.twYarn.setFont(font)
        self.twYarn.setStyleSheet("QTableWidget{\n"
" background-color:rgba(66,66,66,20%);\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"color: #000;\n"
"}\n"
"QTableWidget:item:hover{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"QTableWidget:item:selected\n"
"{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"\n"
"")
        self.twYarn.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twYarn.setTabKeyNavigation(False)
        self.twYarn.setProperty("showDropIndicator", False)
        self.twYarn.setDragDropOverwriteMode(False)
        self.twYarn.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.twYarn.setObjectName("twYarn")
        self.twYarn.setColumnCount(0)
        self.twYarn.setRowCount(0)
        self.verticalLayout_11.addWidget(self.twYarn)
        self.verticalLayout.addWidget(self.groupBox_19)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_14 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.line_27 = QtWidgets.QFrame(self.groupBox_14)
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.verticalLayout_4.addWidget(self.line_27)
        self.label_17 = QtWidgets.QLabel(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.line_28 = QtWidgets.QFrame(self.groupBox_14)
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.verticalLayout_4.addWidget(self.line_28)
        self.fOmega = QtWidgets.QFrame(self.groupBox_14)
        self.fOmega.setStyleSheet(" border-radius:10px;")
        self.fOmega.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fOmega.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fOmega.setObjectName("fOmega")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fOmega)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnOmega = QtWidgets.QPushButton(self.fOmega)
        self.btnOmega.setObjectName("btnOmega")
        self.horizontalLayout_2.addWidget(self.btnOmega)
        self.comOmega = QtWidgets.QComboBox(self.fOmega)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comOmega.setFont(font)
        self.comOmega.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comOmega.setEditable(True)
        self.comOmega.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comOmega.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comOmega.setObjectName("comOmega")
        self.horizontalLayout_2.addWidget(self.comOmega)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.fOmega)
        self.twOmega = QtWidgets.QTableWidget(self.groupBox_14)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.twOmega.setFont(font)
        self.twOmega.setStyleSheet("QTableWidget{\n"
" background-color:rgba(66,66,66,20%);\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"color: #000;\n"
"}\n"
"QTableWidget:item:hover{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"QTableWidget:item:selected\n"
"{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"\n"
"")
        self.twOmega.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twOmega.setTabKeyNavigation(False)
        self.twOmega.setProperty("showDropIndicator", False)
        self.twOmega.setDragDropOverwriteMode(False)
        self.twOmega.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.twOmega.setObjectName("twOmega")
        self.twOmega.setColumnCount(0)
        self.twOmega.setRowCount(0)
        self.verticalLayout_4.addWidget(self.twOmega)
        self.verticalLayout_2.addWidget(self.groupBox_14)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_15 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.line_40 = QtWidgets.QFrame(self.groupBox_15)
        self.line_40.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.verticalLayout_10.addWidget(self.line_40)
        self.label_41 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_10.addWidget(self.label_41)
        self.line_41 = QtWidgets.QFrame(self.groupBox_15)
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.verticalLayout_10.addWidget(self.line_41)
        self.fCloth = QtWidgets.QFrame(self.groupBox_15)
        self.fCloth.setStyleSheet(" border-radius:10px;")
        self.fCloth.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fCloth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fCloth.setObjectName("fCloth")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.fCloth)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnCloth = QtWidgets.QPushButton(self.fCloth)
        self.btnCloth.setObjectName("btnCloth")
        self.horizontalLayout_4.addWidget(self.btnCloth)
        self.comCloth = QtWidgets.QComboBox(self.fCloth)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comCloth.setFont(font)
        self.comCloth.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comCloth.setEditable(True)
        self.comCloth.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comCloth.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comCloth.setObjectName("comCloth")
        self.horizontalLayout_4.addWidget(self.comCloth)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout_10.addWidget(self.fCloth)
        self.twCloth = QtWidgets.QTableWidget(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.twCloth.setFont(font)
        self.twCloth.setStyleSheet("QTableWidget{\n"
" background-color:rgba(66,66,66,20%);\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"color: #000;\n"
"}\n"
"QTableWidget:item:hover{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"QTableWidget:item:selected\n"
"{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"\n"
"")
        self.twCloth.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twCloth.setTabKeyNavigation(False)
        self.twCloth.setProperty("showDropIndicator", False)
        self.twCloth.setDragDropOverwriteMode(False)
        self.twCloth.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.twCloth.setObjectName("twCloth")
        self.twCloth.setColumnCount(0)
        self.twCloth.setRowCount(0)
        self.verticalLayout_10.addWidget(self.twCloth)
        self.verticalLayout_3.addWidget(self.groupBox_15)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_13 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,30%);\n"
"}")
        self.groupBox_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setSpacing(3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.rbOriginal = QtWidgets.QRadioButton(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbOriginal.setFont(font)
        self.rbOriginal.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbOriginal.setChecked(True)
        self.rbOriginal.setObjectName("rbOriginal")
        self.verticalLayout_15.addWidget(self.rbOriginal)
        self.rbEdit = QtWidgets.QRadioButton(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rbEdit.setFont(font)
        self.rbEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbEdit.setObjectName("rbEdit")
        self.verticalLayout_15.addWidget(self.rbEdit)
        self.line_5 = QtWidgets.QFrame(self.groupBox_13)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_15.addWidget(self.line_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.btnEdit = QtWidgets.QToolButton(self.groupBox_13)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout_10.addWidget(self.btnEdit)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_10)
        self.verticalLayout_15.setStretch(3, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout_15)
        self.lblName = QtWidgets.QLineEdit(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblName.sizePolicy().hasHeightForWidth())
        self.lblName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lblName.setFont(font)
        self.lblName.setStyleSheet(" background-color:rgba(66,66,66,0%);\n"
"")
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setReadOnly(True)
        self.lblName.setObjectName("lblName")
        self.horizontalLayout_11.addWidget(self.lblName)
        self.horizontalLayout_11.setStretch(1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_13)
        self.groupBox_54 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_54.setTitle("")
        self.groupBox_54.setObjectName("groupBox_54")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_54)
        self.verticalLayout_5.setContentsMargins(-1, 7, -1, 7)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_54)
        self.groupBox_4.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_17.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_17.setTitle("")
        self.groupBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_17.setObjectName("groupBox_17")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_17)
        self.horizontalLayout_12.setContentsMargins(7, 7, 7, 7)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.line_3 = QtWidgets.QFrame(self.groupBox_17)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_14.addWidget(self.line_3)
        self.txtSlaesCloth = QtWidgets.QLineEdit(self.groupBox_17)
        self.txtSlaesCloth.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSlaesCloth.setFont(font)
        self.txtSlaesCloth.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSlaesCloth.setReadOnly(True)
        self.txtSlaesCloth.setObjectName("txtSlaesCloth")
        self.verticalLayout_14.addWidget(self.txtSlaesCloth)
        self.comSalesCloth = QtWidgets.QComboBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comSalesCloth.setFont(font)
        self.comSalesCloth.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comSalesCloth.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comSalesCloth.setEditable(True)
        self.comSalesCloth.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comSalesCloth.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comSalesCloth.setObjectName("comSalesCloth")
        self.verticalLayout_14.addWidget(self.comSalesCloth)
        self.horizontalLayout_12.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(self.groupBox_17)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_13.addWidget(self.line_2)
        self.txtSlaesOmega = QtWidgets.QLineEdit(self.groupBox_17)
        self.txtSlaesOmega.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSlaesOmega.setFont(font)
        self.txtSlaesOmega.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSlaesOmega.setReadOnly(True)
        self.txtSlaesOmega.setObjectName("txtSlaesOmega")
        self.verticalLayout_13.addWidget(self.txtSlaesOmega)
        self.comSalesOmega = QtWidgets.QComboBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comSalesOmega.setFont(font)
        self.comSalesOmega.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comSalesOmega.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comSalesOmega.setEditable(True)
        self.comSalesOmega.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comSalesOmega.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comSalesOmega.setObjectName("comSalesOmega")
        self.verticalLayout_13.addWidget(self.comSalesOmega)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.groupBox_17)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_8.addWidget(self.line)
        self.txtSlaesYarn = QtWidgets.QLineEdit(self.groupBox_17)
        self.txtSlaesYarn.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSlaesYarn.setFont(font)
        self.txtSlaesYarn.setAlignment(QtCore.Qt.AlignCenter)
        self.txtSlaesYarn.setReadOnly(True)
        self.txtSlaesYarn.setObjectName("txtSlaesYarn")
        self.verticalLayout_8.addWidget(self.txtSlaesYarn)
        self.comSalesYarn = QtWidgets.QComboBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comSalesYarn.setFont(font)
        self.comSalesYarn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comSalesYarn.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comSalesYarn.setEditable(True)
        self.comSalesYarn.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comSalesYarn.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comSalesYarn.setObjectName("comSalesYarn")
        self.verticalLayout_8.addWidget(self.comSalesYarn)
        self.horizontalLayout_12.addLayout(self.verticalLayout_8)
        self.horizontalLayout_3.addWidget(self.groupBox_17)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_43 = QtWidgets.QGroupBox(self.groupBox_54)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_43.setFont(font)
        self.groupBox_43.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_43.setObjectName("groupBox_43")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_43)
        self.horizontalLayout_13.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.comBranch = QtWidgets.QComboBox(self.groupBox_43)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comBranch.setFont(font)
        self.comBranch.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comBranch.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comBranch.setEditable(True)
        self.comBranch.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comBranch.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comBranch.setObjectName("comBranch")
        self.horizontalLayout_13.addWidget(self.comBranch)
        self.txtBranch = QtWidgets.QLineEdit(self.groupBox_43)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtBranch.setFont(font)
        self.txtBranch.setReadOnly(True)
        self.txtBranch.setObjectName("txtBranch")
        self.horizontalLayout_13.addWidget(self.txtBranch)
        self.label_15 = QtWidgets.QLabel(self.groupBox_43)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_13.setStretch(0, 1)
        self.horizontalLayout_13.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_43)
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_54)
        self.groupBox_20.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_20.setObjectName("groupBox_20")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_20)
        self.horizontalLayout_8.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.txtContactPerson = QtWidgets.QLineEdit(self.groupBox_20)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtContactPerson.setFont(font)
        self.txtContactPerson.setReadOnly(True)
        self.txtContactPerson.setObjectName("txtContactPerson")
        self.horizontalLayout_8.addWidget(self.txtContactPerson)
        self.label_22 = QtWidgets.QLabel(self.groupBox_20)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.verticalLayout_5.addWidget(self.groupBox_20)
        self.groupBox_45 = QtWidgets.QGroupBox(self.groupBox_54)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_45.setFont(font)
        self.groupBox_45.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_45.setTitle("")
        self.groupBox_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_45.setObjectName("groupBox_45")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_45)
        self.horizontalLayout_14.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.txtArea = QtWidgets.QLineEdit(self.groupBox_45)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtArea.setFont(font)
        self.txtArea.setReadOnly(True)
        self.txtArea.setObjectName("txtArea")
        self.horizontalLayout_14.addWidget(self.txtArea)
        self.label_16 = QtWidgets.QLabel(self.groupBox_45)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_14.addWidget(self.label_16)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_5.addWidget(self.groupBox_45)
        self.groupBox_42 = QtWidgets.QGroupBox(self.groupBox_54)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_42.setFont(font)
        self.groupBox_42.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_42.setTitle("")
        self.groupBox_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_42.setObjectName("groupBox_42")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_42)
        self.horizontalLayout_9.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.txtAdrress = QtWidgets.QLineEdit(self.groupBox_42)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtAdrress.setFont(font)
        self.txtAdrress.setReadOnly(True)
        self.txtAdrress.setObjectName("txtAdrress")
        self.horizontalLayout_9.addWidget(self.txtAdrress)
        self.label_14 = QtWidgets.QLabel(self.groupBox_42)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.verticalLayout_5.addWidget(self.groupBox_42)
        self.groupBox_44 = QtWidgets.QGroupBox(self.groupBox_54)
        self.groupBox_44.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_44.setTitle("")
        self.groupBox_44.setObjectName("groupBox_44")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_44)
        self.horizontalLayout_15.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.txtMail = QtWidgets.QLineEdit(self.groupBox_44)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtMail.setFont(font)
        self.txtMail.setReadOnly(True)
        self.txtMail.setObjectName("txtMail")
        self.horizontalLayout_15.addWidget(self.txtMail)
        self.label_20 = QtWidgets.QLabel(self.groupBox_44)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.verticalLayout_5.addWidget(self.groupBox_44)
        self.groupBox_41 = QtWidgets.QGroupBox(self.groupBox_54)
        self.groupBox_41.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_41.setTitle("")
        self.groupBox_41.setObjectName("groupBox_41")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_41)
        self.horizontalLayout_5.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.txtPhone4 = QtWidgets.QLineEdit(self.groupBox_41)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPhone4.setFont(font)
        self.txtPhone4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtPhone4.setReadOnly(True)
        self.txtPhone4.setObjectName("txtPhone4")
        self.horizontalLayout_5.addWidget(self.txtPhone4)
        self.txtPhone3 = QtWidgets.QLineEdit(self.groupBox_41)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPhone3.setFont(font)
        self.txtPhone3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtPhone3.setReadOnly(True)
        self.txtPhone3.setObjectName("txtPhone3")
        self.horizontalLayout_5.addWidget(self.txtPhone3)
        self.txtPhone2 = QtWidgets.QLineEdit(self.groupBox_41)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPhone2.setFont(font)
        self.txtPhone2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtPhone2.setReadOnly(True)
        self.txtPhone2.setObjectName("txtPhone2")
        self.horizontalLayout_5.addWidget(self.txtPhone2)
        self.txtPhone1 = QtWidgets.QLineEdit(self.groupBox_41)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtPhone1.setFont(font)
        self.txtPhone1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtPhone1.setObjectName("txtPhone1")
        self.horizontalLayout_5.addWidget(self.txtPhone1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_41)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout_5.addWidget(self.groupBox_41)
        self.groupBox_52 = QtWidgets.QGroupBox(self.groupBox_54)
        self.groupBox_52.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_52.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_52.setObjectName("groupBox_52")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout(self.groupBox_52)
        self.horizontalLayout_38.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.comCustType = QtWidgets.QComboBox(self.groupBox_52)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comCustType.setFont(font)
        self.comCustType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comCustType.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comCustType.setEditable(True)
        self.comCustType.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comCustType.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comCustType.setObjectName("comCustType")
        self.horizontalLayout_38.addWidget(self.comCustType)
        self.txtCustType = QtWidgets.QLineEdit(self.groupBox_52)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtCustType.setFont(font)
        self.txtCustType.setReadOnly(True)
        self.txtCustType.setObjectName("txtCustType")
        self.horizontalLayout_38.addWidget(self.txtCustType)
        self.label_40 = QtWidgets.QLabel(self.groupBox_52)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_38.addWidget(self.label_40)
        self.horizontalLayout_38.setStretch(0, 1)
        self.horizontalLayout_38.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_52)
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_54)
        self.groupBox_25.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_25.setTitle("")
        self.groupBox_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_25.setObjectName("groupBox_25")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.groupBox_25)
        self.horizontalLayout_17.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.comSize = QtWidgets.QComboBox(self.groupBox_25)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comSize.setFont(font)
        self.comSize.setFocusPolicy(QtCore.Qt.NoFocus)
        self.comSize.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comSize.setEditable(True)
        self.comSize.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comSize.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comSize.setObjectName("comSize")
        self.horizontalLayout_17.addWidget(self.comSize)
        self.txtSize = QtWidgets.QLineEdit(self.groupBox_25)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txtSize.setFont(font)
        self.txtSize.setReadOnly(True)
        self.txtSize.setObjectName("txtSize")
        self.horizontalLayout_17.addWidget(self.txtSize)
        self.label_24 = QtWidgets.QLabel(self.groupBox_25)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_25)
        self.verticalLayout_6.addWidget(self.groupBox_54)
        self.groupBox_16 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_24.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_24.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_24.setTitle("")
        self.groupBox_24.setObjectName("groupBox_24")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_24)
        self.verticalLayout_9.setContentsMargins(6, 5, 6, 5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cbYarn = QtWidgets.QCheckBox(self.groupBox_24)
        self.cbYarn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbYarn.sizePolicy().hasHeightForWidth())
        self.cbYarn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbYarn.setFont(font)
        self.cbYarn.setCheckable(True)
        self.cbYarn.setObjectName("cbYarn")
        self.verticalLayout_9.addWidget(self.cbYarn)
        self.line_4 = QtWidgets.QFrame(self.groupBox_24)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.cbOmega = QtWidgets.QCheckBox(self.groupBox_24)
        self.cbOmega.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOmega.sizePolicy().hasHeightForWidth())
        self.cbOmega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbOmega.setFont(font)
        self.cbOmega.setCheckable(True)
        self.cbOmega.setObjectName("cbOmega")
        self.verticalLayout_9.addWidget(self.cbOmega)
        self.line_6 = QtWidgets.QFrame(self.groupBox_24)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_9.addWidget(self.line_6)
        self.cbCloth = QtWidgets.QCheckBox(self.groupBox_24)
        self.cbCloth.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbCloth.sizePolicy().hasHeightForWidth())
        self.cbCloth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbCloth.setFont(font)
        self.cbCloth.setStyleSheet("")
        self.cbCloth.setIconSize(QtCore.QSize(50, 50))
        self.cbCloth.setCheckable(True)
        self.cbCloth.setObjectName("cbCloth")
        self.verticalLayout_9.addWidget(self.cbCloth)
        self.verticalLayout_12.addWidget(self.groupBox_24)
        self.verticalLayout_6.addWidget(self.groupBox_16)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSave = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnPrint = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnPrint.setFont(font)
        self.btnPrint.setObjectName("btnPrint")
        self.horizontalLayout.addWidget(self.btnPrint)
        self.btnPrev = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnPrev.setFont(font)
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout.addWidget(self.btnPrev)
        self.btnCancle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnCancle.setFont(font)
        self.btnCancle.setObjectName("btnCancle")
        self.horizontalLayout.addWidget(self.btnCancle)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_6.setStretch(0, 1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_7.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(details)
        QtCore.QMetaObject.connectSlotsByName(details)

    def retranslateUi(self, details):
        _translate = QtCore.QCoreApplication.translate
        details.setWindowTitle(_translate("details", "Details"))
        self.label_42.setText(_translate("details", "اصناف الغزل"))
        self.btnYarn.setText(_translate("details", ".."))
        self.label_17.setText(_translate("details", "اصناف اوميجا"))
        self.btnOmega.setText(_translate("details", ".."))
        self.label_41.setText(_translate("details", "اصناف القماش"))
        self.btnCloth.setText(_translate("details", ".."))
        self.groupBox_13.setTitle(_translate("details", "*"))
        self.rbOriginal.setText(_translate("details", "الاصل"))
        self.rbEdit.setText(_translate("details", "التعديل"))
        self.btnEdit.setText(_translate("details", "..."))
        self.lblName.setText(_translate("details", "Name"))
        self.groupBox_4.setTitle(_translate("details", "*"))
        self.label_3.setText(_translate("details", "مسئول مبيعات القماش"))
        self.label_2.setText(_translate("details", "مسئول مبيعات اوميجا"))
        self.label.setText(_translate("details", "مسئول مبيعات الغزل"))
        self.label_9.setText(_translate("details", "مسؤل المبيعات"))
        self.groupBox_43.setTitle(_translate("details", "*"))
        self.label_15.setText(_translate("details", "عميل فرع"))
        self.groupBox_20.setTitle(_translate("details", "*"))
        self.label_22.setText(_translate("details", "مسئول التواصل"))
        self.label_16.setText(_translate("details", "المنطقة"))
        self.label_14.setText(_translate("details", "العنوان"))
        self.label_20.setText(_translate("details", "البريد الاليكتروني"))
        self.label_11.setText(_translate("details", "رقم الهاتف"))
        self.groupBox_52.setTitle(_translate("details", "*"))
        self.label_40.setText(_translate("details", "نوع العميل"))
        self.label_24.setText(_translate("details", "الحجم"))
        self.groupBox_16.setTitle(_translate("details", "*"))
        self.cbYarn.setText(_translate("details", "شركة الغزل"))
        self.cbOmega.setText(_translate("details", "شركة اوميجا"))
        self.cbCloth.setText(_translate("details", "القماش "))
        self.btnSave.setText(_translate("details", "حفظ"))
        self.btnPrint.setText(_translate("details", "طباعه"))
        self.btnPrev.setText(_translate("details", "عرض"))
        self.btnCancle.setText(_translate("details", "الغاء"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    details = QtWidgets.QWidget()
    ui = Ui_details()
    ui.setupUi(details)
    details.show()
    sys.exit(app.exec_())
