# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1307, 965)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffff;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"    color: #0000;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #3E2723;\n"
"    background-color: #D7CCC8;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"   background-color: white;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"   background-color: white;\n"
"}\n"
"QMenuBar{\n"
"    background: #BCAAA4;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: #BCAAA4;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    color: #fff;\n"
"    background: #BCAAA4;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"     border: 1px solid #000;\n"
"    background-color: #D7CCC8;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: white;\n"
"    color:#000;\n"
"}\n"
"\n"
"\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0.1 #646464, stop: 1 #5d5d5d);\n"
"}\n"
"\n"
"QWidget:focus\n"
"{\n"
"    /*border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"   /* background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;*/\n"
"\n"
"background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #000;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
" /*   border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"   /* background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);*/\n"
"    selection-background-color: #000;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"   /* selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);*/\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"\n"
"background-color: #000000 ;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:rgba(66,66,66,0%);\n"
"border-radius: 5px;\n"
"\n"
"}\n"
"\n"
"QGroupBox{\n"
"  background-color: #BCAAA4;\n"
"  border-radius:15px;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #3E2723;\n"
"    width: 5px;\n"
"    border-radius: 5px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton{\n"
"background-color:rgba(66,66,66,0%);\n"
"\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 6;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox\n"
"{\n"
"    border-radius: 6;\n"
"    padding:5px\n"
"\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    \n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_12.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_8 = QtWidgets.QFrame(self.groupBox_12)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_2.addWidget(self.line_8)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line_25 = QtWidgets.QFrame(self.groupBox_12)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.horizontalLayout_2.addWidget(self.line_25)
        self.verticalLayout_8.addWidget(self.groupBox_12)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.btnRefresh = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRefresh.sizePolicy().hasHeightForWidth())
        self.btnRefresh.setSizePolicy(sizePolicy)
        self.btnRefresh.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setObjectName("btnRefresh")
        self.horizontalLayout_34.addWidget(self.btnRefresh)
        self.btnSearchData = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSearchData.sizePolicy().hasHeightForWidth())
        self.btnSearchData.setSizePolicy(sizePolicy)
        self.btnSearchData.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnSearchData.setFont(font)
        self.btnSearchData.setObjectName("btnSearchData")
        self.horizontalLayout_34.addWidget(self.btnSearchData)
        self.lcdNumber = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 42))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("border-radius: 6;")
        self.lcdNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.lcdNumber.setReadOnly(True)
        self.lcdNumber.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.lcdNumber.setMaximum(9999)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_34.addWidget(self.lcdNumber)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_13.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line_9 = QtWidgets.QFrame(self.groupBox_13)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_3.addWidget(self.line_9)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lblInternet = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblInternet.setFont(font)
        self.lblInternet.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInternet.setObjectName("lblInternet")
        self.verticalLayout_5.addWidget(self.lblInternet)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.line_26 = QtWidgets.QFrame(self.groupBox_13)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.horizontalLayout_3.addWidget(self.line_26)
        self.horizontalLayout_34.addWidget(self.groupBox_13)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.comPhone = QtWidgets.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comPhone.setFont(font)
        self.comPhone.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comPhone.setEditable(True)
        self.comPhone.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comPhone.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comPhone.setObjectName("comPhone")
        self.horizontalLayout_13.addWidget(self.comPhone)
        self.line_31 = QtWidgets.QFrame(self.groupBox_8)
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.horizontalLayout_13.addWidget(self.line_31)
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.horizontalLayout_13.setStretch(0, 10)
        self.horizontalLayout_34.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comName = QtWidgets.QComboBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comName.setFont(font)
        self.comName.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comName.setEditable(True)
        self.comName.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comName.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.comName.setObjectName("comName")
        self.horizontalLayout.addWidget(self.comName)
        self.line_21 = QtWidgets.QFrame(self.groupBox_7)
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout.addWidget(self.line_21)
        self.label = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout_34.addWidget(self.groupBox_7)
        self.horizontalLayout_34.setStretch(0, 1)
        self.horizontalLayout_34.setStretch(4, 5)
        self.horizontalLayout_34.setStretch(5, 5)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.line_16 = QtWidgets.QFrame(self.tab)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_8.addWidget(self.line_16)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_24 = QtWidgets.QFrame(self.groupBox_6)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.verticalLayout.addWidget(self.line_24)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line_23 = QtWidgets.QFrame(self.groupBox_6)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.verticalLayout.addWidget(self.line_23)
        self.twResalt = QtWidgets.QTableWidget(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.twResalt.setFont(font)
        self.twResalt.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.twResalt.setStyleSheet("QTableWidget{\n"
" background-color:rgba(66,66,66,20%);\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"color: #000;\n"
"}\n"
"QTableWidget:item:hover{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"QTableWidget:item:selected\n"
"{\n"
"    background-color: white;\n"
"    color: #000;\n"
"}\n"
"\n"
"\n"
"")
        self.twResalt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.twResalt.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twResalt.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twResalt.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twResalt.setGridStyle(QtCore.Qt.DashLine)
        self.twResalt.setObjectName("twResalt")
        self.twResalt.setColumnCount(0)
        self.twResalt.setRowCount(0)
        self.twResalt.horizontalHeader().setDefaultSectionSize(131)
        self.twResalt.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.twResalt)
        self.horizontalLayout_43.addWidget(self.groupBox_6)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 306, 768))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_53 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_53.setTitle("")
        self.groupBox_53.setObjectName("groupBox_53")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_53)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_9.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comLocation = QtWidgets.QComboBox(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comLocation.setFont(font)
        self.comLocation.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comLocation.setEditable(True)
        self.comLocation.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comLocation.setObjectName("comLocation")
        self.horizontalLayout_14.addWidget(self.comLocation)
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.groupBox_9)
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_23.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_23.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_23.setTitle("")
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cbYarn = QtWidgets.QCheckBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbYarn.sizePolicy().hasHeightForWidth())
        self.cbYarn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbYarn.setFont(font)
        self.cbYarn.setObjectName("cbYarn")
        self.horizontalLayout_4.addWidget(self.cbYarn)
        self.btnYarn = QtWidgets.QPushButton(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnYarn.sizePolicy().hasHeightForWidth())
        self.btnYarn.setSizePolicy(sizePolicy)
        self.btnYarn.setObjectName("btnYarn")
        self.horizontalLayout_4.addWidget(self.btnYarn)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.groupBox_23)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.cbOmega = QtWidgets.QCheckBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbOmega.sizePolicy().hasHeightForWidth())
        self.cbOmega.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbOmega.setFont(font)
        self.cbOmega.setObjectName("cbOmega")
        self.horizontalLayout_5.addWidget(self.cbOmega)
        self.btnOmega = QtWidgets.QPushButton(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOmega.sizePolicy().hasHeightForWidth())
        self.btnOmega.setSizePolicy(sizePolicy)
        self.btnOmega.setObjectName("btnOmega")
        self.horizontalLayout_5.addWidget(self.btnOmega)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.groupBox_23)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbColth = QtWidgets.QCheckBox(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbColth.sizePolicy().hasHeightForWidth())
        self.cbColth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbColth.setFont(font)
        self.cbColth.setStyleSheet("")
        self.cbColth.setIconSize(QtCore.QSize(50, 50))
        self.cbColth.setObjectName("cbColth")
        self.horizontalLayout_6.addWidget(self.cbColth)
        self.btnCloth = QtWidgets.QPushButton(self.groupBox_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCloth.sizePolicy().hasHeightForWidth())
        self.btnCloth.setSizePolicy(sizePolicy)
        self.btnCloth.setObjectName("btnCloth")
        self.horizontalLayout_6.addWidget(self.btnCloth)
        self.horizontalLayout_6.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_23)
        self.swCates = QtWidgets.QStackedWidget(self.groupBox_53)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swCates.sizePolicy().hasHeightForWidth())
        self.swCates.setSizePolicy(sizePolicy)
        self.swCates.setMinimumSize(QtCore.QSize(0, 136))
        self.swCates.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.swCates.setAutoFillBackground(False)
        self.swCates.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.swCates.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.swCates.setMidLineWidth(0)
        self.swCates.setObjectName("swCates")
        self.pYarn = QtWidgets.QWidget()
        self.pYarn.setObjectName("pYarn")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.pYarn)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.pYarn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 243, 396))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_9.addWidget(self.line_4)
        self.cateYarnAll = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateYarnAll.sizePolicy().hasHeightForWidth())
        self.cateYarnAll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateYarnAll.setFont(font)
        self.cateYarnAll.setObjectName("cateYarnAll")
        self.verticalLayout_9.addWidget(self.cateYarnAll)
        self.cateSbun = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateSbun.sizePolicy().hasHeightForWidth())
        self.cateSbun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateSbun.setFont(font)
        self.cateSbun.setObjectName("cateSbun")
        self.verticalLayout_9.addWidget(self.cateSbun)
        self.cateCotton = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateCotton.sizePolicy().hasHeightForWidth())
        self.cateCotton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateCotton.setFont(font)
        self.cateCotton.setObjectName("cateCotton")
        self.verticalLayout_9.addWidget(self.cateCotton)
        self.cateFesskoz = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateFesskoz.sizePolicy().hasHeightForWidth())
        self.cateFesskoz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateFesskoz.setFont(font)
        self.cateFesskoz.setObjectName("cateFesskoz")
        self.verticalLayout_9.addWidget(self.cateFesskoz)
        self.cateLekra = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateLekra.sizePolicy().hasHeightForWidth())
        self.cateLekra.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateLekra.setFont(font)
        self.cateLekra.setObjectName("cateLekra")
        self.verticalLayout_9.addWidget(self.cateLekra)
        self.cateShoayrat = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateShoayrat.sizePolicy().hasHeightForWidth())
        self.cateShoayrat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateShoayrat.setFont(font)
        self.cateShoayrat.setObjectName("cateShoayrat")
        self.verticalLayout_9.addWidget(self.cateShoayrat)
        self.cateMobant = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateMobant.sizePolicy().hasHeightForWidth())
        self.cateMobant.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateMobant.setFont(font)
        self.cateMobant.setObjectName("cateMobant")
        self.verticalLayout_9.addWidget(self.cateMobant)
        self.catePolyster = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catePolyster.sizePolicy().hasHeightForWidth())
        self.catePolyster.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.catePolyster.setFont(font)
        self.catePolyster.setObjectName("catePolyster")
        self.verticalLayout_9.addWidget(self.catePolyster)
        self.cateMix = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateMix.sizePolicy().hasHeightForWidth())
        self.cateMix.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateMix.setFont(font)
        self.cateMix.setObjectName("cateMix")
        self.verticalLayout_9.addWidget(self.cateMix)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.swCates.addWidget(self.pYarn)
        self.pOmega = QtWidgets.QWidget()
        self.pOmega.setObjectName("pOmega")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pOmega)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.pOmega)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(-80, 0, 161, 396))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.line_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_12.addWidget(self.line_6)
        self.cateOmegaAll = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateOmegaAll.sizePolicy().hasHeightForWidth())
        self.cateOmegaAll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateOmegaAll.setFont(font)
        self.cateOmegaAll.setObjectName("cateOmegaAll")
        self.verticalLayout_12.addWidget(self.cateOmegaAll)
        self.cateHyaka = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateHyaka.sizePolicy().hasHeightForWidth())
        self.cateHyaka.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateHyaka.setFont(font)
        self.cateHyaka.setObjectName("cateHyaka")
        self.verticalLayout_12.addWidget(self.cateHyaka)
        self.cateHarer = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateHarer.sizePolicy().hasHeightForWidth())
        self.cateHarer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateHarer.setFont(font)
        self.cateHarer.setObjectName("cateHarer")
        self.verticalLayout_12.addWidget(self.cateHarer)
        self.catePolysterTatrez = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catePolysterTatrez.sizePolicy().hasHeightForWidth())
        self.catePolysterTatrez.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.catePolysterTatrez.setFont(font)
        self.catePolysterTatrez.setObjectName("catePolysterTatrez")
        self.verticalLayout_12.addWidget(self.catePolysterTatrez)
        self.cateCerma = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateCerma.sizePolicy().hasHeightForWidth())
        self.cateCerma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateCerma.setFont(font)
        self.cateCerma.setObjectName("cateCerma")
        self.verticalLayout_12.addWidget(self.cateCerma)
        self.cateQassab = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateQassab.sizePolicy().hasHeightForWidth())
        self.cateQassab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateQassab.setFont(font)
        self.cateQassab.setObjectName("cateQassab")
        self.verticalLayout_12.addWidget(self.cateQassab)
        self.cateGoma = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateGoma.sizePolicy().hasHeightForWidth())
        self.cateGoma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateGoma.setFont(font)
        self.cateGoma.setObjectName("cateGoma")
        self.verticalLayout_12.addWidget(self.cateGoma)
        self.cateSpray = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateSpray.sizePolicy().hasHeightForWidth())
        self.cateSpray.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateSpray.setFont(font)
        self.cateSpray.setObjectName("cateSpray")
        self.verticalLayout_12.addWidget(self.cateSpray)
        self.cateFazlin = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cateFazlin.sizePolicy().hasHeightForWidth())
        self.cateFazlin.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cateFazlin.setFont(font)
        self.cateFazlin.setObjectName("cateFazlin")
        self.verticalLayout_12.addWidget(self.cateFazlin)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.addWidget(self.scrollArea_2)
        self.swCates.addWidget(self.pOmega)
        self.pCloth = QtWidgets.QWidget()
        self.pCloth.setObjectName("pCloth")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.pCloth)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.pCloth)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(-83, 0, 164, 84))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.line_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_14.addWidget(self.line_10)
        self.cbYarn_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbYarn_22.sizePolicy().hasHeightForWidth())
        self.cbYarn_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbYarn_22.setFont(font)
        self.cbYarn_22.setObjectName("cbYarn_22")
        self.verticalLayout_14.addWidget(self.cbYarn_22)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_11.addWidget(self.scrollArea_3)
        self.swCates.addWidget(self.pCloth)
        self.verticalLayout_3.addWidget(self.swCates)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_53)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox_10.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"padding-top:20px\n"
"}")
        self.groupBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(False)
        self.groupBox_10.setChecked(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_3 = QtWidgets.QFrame(self.groupBox_10)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        self.cbFactory = QtWidgets.QCheckBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFactory.sizePolicy().hasHeightForWidth())
        self.cbFactory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbFactory.setFont(font)
        self.cbFactory.setObjectName("cbFactory")
        self.verticalLayout_6.addWidget(self.cbFactory)
        self.cbTager = QtWidgets.QCheckBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTager.sizePolicy().hasHeightForWidth())
        self.cbTager.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbTager.setFont(font)
        self.cbTager.setObjectName("cbTager")
        self.verticalLayout_6.addWidget(self.cbTager)
        self.cbTgerCloth = QtWidgets.QCheckBox(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTgerCloth.sizePolicy().hasHeightForWidth())
        self.cbTgerCloth.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cbTgerCloth.setFont(font)
        self.cbTgerCloth.setObjectName("cbTgerCloth")
        self.verticalLayout_6.addWidget(self.cbTgerCloth)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_18.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_18.setTitle("")
        self.groupBox_18.setObjectName("groupBox_18")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.groupBox_18)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.comContactPerson = QtWidgets.QComboBox(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comContactPerson.setFont(font)
        self.comContactPerson.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comContactPerson.setEditable(True)
        self.comContactPerson.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comContactPerson.setObjectName("comContactPerson")
        self.horizontalLayout_20.addWidget(self.comContactPerson)
        self.label_23 = QtWidgets.QLabel(self.groupBox_18)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_20.addWidget(self.label_23)
        self.horizontalLayout_20.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_19.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.groupBox_19)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.comSalesPerson = QtWidgets.QComboBox(self.groupBox_19)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.comSalesPerson.setFont(font)
        self.comSalesPerson.setStyleSheet("background-color: #D7CCC8;\n"
"border-width: 1px;\n"
"border-color: #1e1e1e;\n"
"border-radius: 6;\n"
"padding: 3px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"font-size: 17px;\n"
"font-weight: bold;")
        self.comSalesPerson.setEditable(True)
        self.comSalesPerson.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.comSalesPerson.setObjectName("comSalesPerson")
        self.horizontalLayout_22.addWidget(self.comSalesPerson)
        self.label_25 = QtWidgets.QLabel(self.groupBox_19)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_22.addWidget(self.label_25)
        self.horizontalLayout_22.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.groupBox_19)
        self.line_17 = QtWidgets.QFrame(self.groupBox_53)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.verticalLayout_3.addWidget(self.line_17)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_53)
        self.groupBox_11.setStyleSheet("QGroupBox{\n"
" background-color:rgba(66,66,66,20%);\n"
"}")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.btnReset = QtWidgets.QPushButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReset.sizePolicy().hasHeightForWidth())
        self.btnReset.setSizePolicy(sizePolicy)
        self.btnReset.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnReset.setFont(font)
        self.btnReset.setObjectName("btnReset")
        self.horizontalLayout_16.addWidget(self.btnReset)
        self.horizontalLayout_16.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 3)
        self.verticalLayout_3.setStretch(3, 1)
        self.verticalLayout_13.addWidget(self.groupBox_53)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_43.addWidget(self.scrollArea_4)
        self.horizontalLayout_43.setStretch(0, 3)
        self.horizontalLayout_43.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_43)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1307, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Customer = QtWidgets.QAction(MainWindow)
        self.actionNew_Customer.setObjectName("actionNew_Customer")
        self.menuFile.addAction(self.actionNew_Customer)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.swCates.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Customers"))
        self.label_15.setText(_translate("MainWindow", "البحث"))
        self.btnRefresh.setText(_translate("MainWindow", "طلبات التعديل"))
        self.btnSearchData.setText(_translate("MainWindow", "البحث"))
        self.lblInternet.setText(_translate("MainWindow", "جارى الاتصال ..."))
        self.label_2.setText(_translate("MainWindow", "رقم الهاتف"))
        self.label.setText(_translate("MainWindow", "اسم العميل "))
        self.label_5.setText(_translate("MainWindow", "النتائج"))
        self.label_19.setText(_translate("MainWindow", "المكان"))
        self.cbYarn.setText(_translate("MainWindow", "شركة الغزل"))
        self.btnYarn.setText(_translate("MainWindow", "..."))
        self.cbOmega.setText(_translate("MainWindow", "شركة اوميجا"))
        self.btnOmega.setText(_translate("MainWindow", "..."))
        self.cbColth.setText(_translate("MainWindow", "مصنع القماش"))
        self.btnCloth.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "اصناف الغزل"))
        self.cateYarnAll.setText(_translate("MainWindow", "الكل"))
        self.cateSbun.setText(_translate("MainWindow", "سبن"))
        self.cateCotton.setText(_translate("MainWindow", "قطن"))
        self.cateFesskoz.setText(_translate("MainWindow", "فسكوز"))
        self.cateLekra.setText(_translate("MainWindow", "ليكرا"))
        self.cateShoayrat.setText(_translate("MainWindow", "شعيرات"))
        self.cateMobant.setText(_translate("MainWindow", "مبنط"))
        self.catePolyster.setText(_translate("MainWindow", "بوليستر"))
        self.cateMix.setText(_translate("MainWindow", "مخلوط"))
        self.label_4.setText(_translate("MainWindow", "اصناف اوميجا"))
        self.cateOmegaAll.setText(_translate("MainWindow", "الكل"))
        self.cateHyaka.setText(_translate("MainWindow", "حياكه"))
        self.cateHarer.setText(_translate("MainWindow", "حرير"))
        self.catePolysterTatrez.setText(_translate("MainWindow", "بوليستر تطريز"))
        self.cateCerma.setText(_translate("MainWindow", "سيرما"))
        self.cateQassab.setText(_translate("MainWindow", "قصب"))
        self.cateGoma.setText(_translate("MainWindow", "جوما"))
        self.cateSpray.setText(_translate("MainWindow", "اسبراي"))
        self.cateFazlin.setText(_translate("MainWindow", "فازلين"))
        self.label_7.setText(_translate("MainWindow", "اصناف مصنع القماش"))
        self.cbYarn_22.setText(_translate("MainWindow", "الكل"))
        self.groupBox_10.setTitle(_translate("MainWindow", "نوع العميل"))
        self.cbFactory.setText(_translate("MainWindow", "مصنع"))
        self.cbTager.setText(_translate("MainWindow", "تاجر"))
        self.cbTgerCloth.setText(_translate("MainWindow", "تاجر قماش"))
        self.label_23.setText(_translate("MainWindow", "مسئول التواصل"))
        self.label_25.setText(_translate("MainWindow", "مسئول المبيعات"))
        self.btnReset.setText(_translate("MainWindow", "تفريغ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "البحث"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew_Customer.setText(_translate("MainWindow", "New Customer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
